---
title: "Programs - R"
output:
  html_document:
    toc: true 
    toc_float: true
---

# R Initial

- To display R code chunks with code and output use: ```{r} x=2 ```
- To display R code output without code use ```{r,echo=F} x=2 ```
- To display R code without output use ```{r,eval=F} x=2 ```

```{r,eval=F}
rm(list=ls()) # Clear variables
if("ggplot2" %in% rownames(installed.packages()) == FALSE) {install.packages("ggplot2")};library(ggplot2)
# Load packages
```

# R Directories and Files

## Create & delete

```{r, eval=F}
wd0 <- getwd() # Get current dirctory
dirname(wd0)  # Gives parent directory of the current one
dir.create("x") # creates directory x in working dir
dir.create(paste(getwd(),"/x/y",sep="")) # creates directory y within x
file.create(paste(getwd(),"/x/y/example.txt",sep="")) # create a text file
file.remove(paste(getwd(),"/x/y/example.txt",sep="")) # remove a file
unlink("x",recursive=T) # delete entire folders
```

## R Reading and Saving Files
```{r, eval=F}

# Function to save figures as pdf or png
pdfOnly<-1;

if(pdfOnly==1){pdf(paste(dir,"/",filename,".pdf",sep=""),width=figWidth_Inch,height=figHeight_Inch)
    print(figure)
    dev.off()} else{
  
    pdf(paste(dir,"/",filename,".pdf",sep=""),width=figWidth_Inch,height=figHeight_Inch)
    print(figure)
    dev.off()
    
    png(paste(dir,"/",filename,".png",sep=""),width=png_Width, height=png_Width*figHeight_Inch/figWidth_Inch, units="px")
    print(figure)
    dev.off()
  }
}

# csv files

read.csv(paste("XXX.csv",sep=""), stringsAsFactors = F, header=F)
write.csv(df,file=paste("XXX.csv",sep=""),row.names=F)

```

# R Manipulate Data

## Reshape Data (Wide, Long)
```{r}
rm(list=ls())

if(!require(reshape2)){install.packages("reshape2")};library(reshape2) # Load packages
if(!require(dplyr)){install.packages("dplyr")};library(dplyr) # Load packages
if(!require(tibble)){install.packages("tibble")};library(tibble) # Load packages

# Create Dummy Data
df<-data.frame(names=c("Z","A","X","W","Z","A","X","W","Z","A","X","W"),
               subname=c("Z1","A1","X1","W1","Z2","A2","X2","W2","Z3","A3","X3","W3"),
               freq=c(10,12,2,5,13,21,23,52,101,122,21,52),
               color=c("blue","red","red","red","green","blue","red","green","blue","red","red","green"));print(df)

# Go from Long to Wide format using dcast
#dcast(data,row1+row2~col1+col2,value.var="value", fun.aggregate=functions (e.g. sum or mean))
df_wide<-dcast(df,names+subname~color,value.var="freq",fun.aggregate=sum,na.rm=T);print(df_wide)

#Go from Wide to Long using melt can ignore measure.vars if want all of them to collapse
#dt3<-melt(dt2, id.vars=c("year","month"), measure.vars=c(""), value.name="",variable.name="Level_m")
df_long<-melt(df_wide, id.vars=c("names","subname"), value.name="freq",variable.name="color");print(df_long)

# Aggregate data to summarize
df_agg<-aggregate(freq~names, data=df_long, sum, na.rm=TRUE); print(df_agg)

# Aggregate over some names only
select_names<-c("Z","X")
df_long_select<-df_long[df_long$name %in% select_names,];head(df_long_select)
df_agg_select<-aggregate(freq~names, data=df_long_select, sum, na.rm=TRUE); print(df_agg_select)

# Load pre-loaded data
data(mtcars);head(mtcars)

# Add rownames as a column
df_mtcars<-as.data.frame(rownames_to_column(mtcars,"model"));head(df_mtcars)
```

## R Subsetting

```{r}
rm(list=ls())

if(!require(reshape2)){install.packages("reshape2")};library(reshape2) # Load packages
if(!require(dplyr)){install.packages("dplyr")};library(dplyr) # Load packages
if(!require(tibble)){install.packages("tibble")};library(tibble) # Load packages

# Create Dummy Data
df<-data.frame(names=c("Z","A","X","W","Z","A","X","W","Z","A","X","W"),
               subname=c("Z1","A1","X1","W1","Z2","A2","X2","W2","Z3","A3","X3","W3"),
               freq=c(10,12,2,5,13,21,23,52,101,122,21,52),
               color=c("blue","red","red","red","green","blue","red","green","blue","red","red","green"));print(df)


# Subset by column
df_select<-subset(df,select=c(subname,freq));print(df_select) # choose the columns
df_selectR<-subset(df,select=-c(subname,freq));print(df_selectR) # remove certain columns

```

# R Colors

[https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf)

[http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf](http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf)


```{r}
# Load Packages
if(!require(graphics)){install.packages("graphics")};library(graphics)
if(!require(graphics)){install.packages("graphics")};library(graphics)

# View a single color quickly
x<-adjustcolor("red", alpha.f = 0.2)
pie(rep(1,12),label=x,col=x)

# R colors
myPalette1<- rainbow(n=12,alpha=0.9)
myPalette2<- heat.colors(n=12,alpha=0.7)
myPalette3<- terrain.colors(n=12,alpha=1)
myPalette4<- topo.colors(n=12,alpha=0.5)
myPalette5<- cm.colors(n=12,alpha=0.6)

# Custom
myPalette6<- c("red","#fdd67b")
myPalette7<- colorRampPalette(c("blue", "yellow","red"))(8) 

pie(rep(1,length(myPalette1)),labels=myPalette1,col=myPalette1)
pie(rep(1,length(myPalette2)),labels=myPalette2,col=myPalette2)
pie(rep(1,length(myPalette3)),labels=myPalette3,col=myPalette3)
pie(rep(1,length(myPalette4)),labels=myPalette4,col=myPalette4)
pie(rep(1,length(myPalette5)),labels=myPalette5,col=myPalette5)
pie(rep(1,length(myPalette6)),labels=myPalette6,col=myPalette6)
pie(rep(1,length(myPalette7)),labels=myPalette7,col=myPalette7)
```


# R Charts

```{r}
rm(list=ls())

if(!require(reshape2)){install.packages("reshape2")};library(reshape2) 
if(!require(dplyr)){install.packages("dplyr")};library(dplyr) 
if(!require(tibble)){install.packages("tibble")};library(tibble)
if(!require(ggplot2)){install.packages("ggplot2")};library(ggplot2) 
if(!require(RColorBrewer)){install.packages("RColorBrewer")};library(RColorBrewer) 
if(!require(scales)){install.packages("scales")};library(scales) # For pretty_breaks


#--------------
# Custom Theme
#--------------
z_theme <<- theme_bw() + 
  theme(text = element_text(family = NULL, face = "plain",colour = "black", 
                             size = 16 ,hjust = 0.5, vjust = 0.5, angle = 0, lineheight = 0.9)
        , axis.text.x =       element_text(size=12)
        , axis.text.y =       element_text(size=12)
        ,axis.title.x =       element_text(vjust = -1, margin=margin(t=1,unit="line"))
        ,axis.title.y =       element_text(angle = 90, vjust = 2, margin=margin(r=1,unit="line"))
        ,legend.key =         element_blank()
        ,legend.text =        element_text(size = rel(1.0), colour = "black")
        ,legend.title =       element_text(size = rel(1.2), face = NULL, hjust = 0, colour = "black")
        ,strip.background =   element_rect(fill = NA, colour = "black")
        ,plot.margin =        unit(c(1, 1, 1, 1), "lines")
        ,plot.title=          element_text(face="bold", hjust=0,size=18,margin = margin(b=20))
        )



#--------------
# Custom Colors
#--------------
# Custom Colors for large unassigned palettes
# Custom Colors https://stackoverflow.com/questions/15282580/how-to-generate-a-number-of-most-distinctive-colors-in-r
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
colorsX_Unassigned= unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
myPalette<-colorsX_Unassigned
pie(rep(1,length(myPalette)),label=names(myPalette),col=myPalette)

# Color scheme for labels in FillLabel if known
colorsX_elec_subsec <- c( "coal" = "#a0237c","gas" = "#25a9e0","oil" = "#d01c2a","biomass" = "#00931d",
                       "nuclear" = "#ef8e27",
                       "geothermal" = "#ad440c",
                       "hydro" = "#fdfa28",
                       "wind" = "#3d86f9",
                       "solar" = "#fdd67b",
                       "refined liquids" = "#507fab")
myPalette<-colorsX_elec_subsec
pie(rep(1,length(myPalette)),label=names(myPalette),col=myPalette)


#---------------
# Charting Functions
#---------------
fig_LineSingle<- function(l1){
  p<-ggplot(l1,aes(x=x,y=NewValue,group=scenario))
  p<-p + z_theme
  p<-p + geom_line(aes(),color="red",stat="identity",position="identity",size=1.5) 
  p<-p + guides(fill = guide_legend(override.aes = list(colour = NULL)))
  p<-p + xlab(eval(parse(text=unique(l1$xLabel)))) + ylab(eval(parse(text=unique(l1$NewUnits))))
  p<-p + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
  p<-p + scale_x_continuous (breaks=(seq(min(range(l1$x))-breakx_majMaster,max(range(l1$x))+breakx_majMaster,by=breakx_majMaster)), 
                             minor_breaks=(seq(min(range(l1$x)),max(range(l1$x)),by=breakx_minMaster)),expand=c(0,breakx_majMaster/2))
  p<-p + scale_y_continuous(breaks = pretty_breaks(n = prettyBreaksyMaster))}


fig_LineMultiple<-function(l1){
  
  paletteX<-get(l1$FillPalette);
  if(useNewLabels==1){
    if(!is.null(names(paletteX))){
      names(paletteX)<-toTitleCase(sub("\\b[a-zA-Z0-9]{1} \\b", "",names(paletteX)))}
    l1$Fill<-toTitleCase(sub("\\b[a-zA-Z0-9]{1} \\b", "",l1$Fill))
  }
  
  p <- ggplot(l1[order((l1$Fill)),],aes(x=x,y=NewValue,group=Fill))
  p <- p + z_theme
  p <- p + geom_line(aes(color=Fill),stat="identity",position="identity",size=1.5) 
  p <- p + guides(color = guide_legend(color=NULL,reverse=T,title=unique(l1$FillLabel)))
  p <- p + xlab(eval(parse(text=unique(l1$xLabel)))) + ylab(eval(parse(text=unique(l1$NewUnits))))
  p <- p + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
  p <- p + scale_x_continuous (breaks=(seq(min(range(l1$x)),max(range(l1$x)),by=breakx_majMaster)), 
                               minor_breaks=(seq(min(range(l1$x)),max(range(l1$x)),by=breakx_minMaster)),expand=c(0,breakx_majMaster/2))
  p <- p +  scale_y_continuous(breaks = pretty_breaks(n = prettyBreaksyMaster))
  p <- p + scale_fill_manual(values=paletteX)
}

fig_Bar<-function(l1){
  
  paletteX<-get(l1$FillPalette);
  if(useNewLabels==1){
    if(!is.null(names(paletteX))){
      names(paletteX)<-toTitleCase(sub("\\b[a-zA-Z0-9]{1} \\b", "",names(paletteX)))}
    l1$Fill<-toTitleCase(sub("\\b[a-zA-Z0-9]{1} \\b", "",l1$Fill))
  }
  
  p <- ggplot(l1[order((l1$Fill)),],aes(x=x,y=NewValue,group=scenario, fill=Fill))
  p <- p + z_theme
  p <- p + geom_bar(aes(), stat="identity",width=0.9*breakx_minMaster)
  p <- p + guides(fill = guide_legend(color=NULL,reverse=T,title=unique(l1$FillLabel)))
  p <- p + xlab(eval(parse(text=unique(l1$xLabel)))) + ylab(eval(parse(text=unique(l1$NewUnits))))
  p <- p + theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))
  p <- p + scale_x_continuous (breaks=(seq(min(range(l1$x)),max(range(l1$x)),by=breakx_majMaster)), 
                               minor_breaks=(seq(min(range(l1$x)),max(range(l1$x)),by=breakx_minMaster)),expand=c(0,breakx_majMaster/2))
  p <- p +  scale_y_continuous(breaks = pretty_breaks(n = prettyBreaksyMaster))
  p <- p + scale_fill_manual(values=paletteX)
}


#--------------
# Master Options
#--------------

# Chart Details
titleOn<-1 # 1 for yes, 0 for no
useNewLabels<- 0 # 1 for new modified labels without letter prefix and capitalized
prettyBreaksyMaster<-5
breakx_majMaster<-10
breakx_minMaster<-5

# PDF details
figWidth_InchMaster<-13
figWidth_StateCharts_Multplier<-2.5
figWidth_FreeScale_Multplier<-1.2
figHeight_InchMaster<-9
figHeight_StateCharts_Multplier<-2
pngWidth=1000
pdfOnly=1

#---------------
# Data Prep 
#---------------

# Load pre-loaded data
lx<-data.frame(scenario="Scenario1",
               regions=rep(x=c("R1","R2","R3","R4"),each=4*2*11),
               subsector=rep(x=c("coal","gas","wind","solar"),each=2*11),
               technology=rep(x=c("coal IGCC","coal CCS","gas CCGT","gas Turbine","wind onshore","wind offshore","solar pv","solar CSP"),each=11),
               year=seq(from=2000,to=2050,by=5),
               elecProd=round(rnorm(88,0,100),2))


# Add columns for your Fill, FillLabel, FillPalette, NewValue and NewUnits
# Example Want to study the elecProd for the sectors and regions
# So elecProd will be our NewValue and NewUnits will be MWh
# X will be the years and xLabel will be "Years"
# We will aggregate the data by taking the sum over all regions
# Then we will look at the aggregated data for each region (facets)
# Then we will look at the data for in bars for the different subsectors for all regions stacked with a total
# Then we will look at the data for in bars for the different subsectors for all regions dodged with a total
# Then we will look at the data for in multiple lines for the different subsectors for all regions

lx$NewValue<-lx$elecProd
lx$NewUnits<-"~MWh"  # Use ~ for spaces ^ for superscripts _ for subscripts. Will be parsed later
lx$x<-lx$year
lx$xLabel<-"~Year" # Use ~ for spaces ^ for superscripts _ for subscripts. Will be parsed later
lx$Fill<-lx$subsector
lx$FillLabel<-"Subsector"
lx$FillPalette<-"colorsX_Unassigned"


#---------------
# Aggregate Data for Plots
#---------------

lOrig<-lx # unedited data

# Plot mean weight for all models
# subset the dataframe to keep only relevant columns then aggregate by taking mean
l1<-subset(lx,select=c(scenario,NewValue,NewUnits,x,xLabel))
l1<-aggregate(NewValue~., data=l1, sum, na.rm=TRUE)
p_line<-fig_LineSingle(l1); print(p_line)

# Plot mean weight for each model
# subset the dataframe to keep only relevant columns then aggregate by taking mean
l1<-subset(lx,select=c(Fill,FillLabel,FillPalette,scenario,NewValue,NewUnits,x,xLabel))
l1<-aggregate(NewValue~., data=l1, sum, na.rm=TRUE)
p_lineMulti<-fig_LineMultiple(l1); print(p_lineMulti)

# Plot the bar plot
# subset the dataframe to keep only relevant columns then aggregate by taking mean
l1<-subset(lx,select=c(Fill,FillLabel,FillPalette,scenario,NewValue,NewUnits,x,xLabel))
l1<-aggregate(NewValue~., data=l1, sum, na.rm=TRUE)
p_bar<-fig_Bar(l1); print(p_bar)


# To print to PDF or PNG
#pdf("figure.pdf",width=figWidth_Inch,height=figHeight_Inch)
#    print(p)
#dev.off()

#png(paste(dir,"/",filename,".png",sep=""),width=png_Width, height=png_Width*figHeight_Inch/figWidth_Inch, units="px")
#   print(figure)
#dev.off()
          

```

# R Maps - Spatial




